version: "3"
services:
  opencv:
    # replace username/repo:tag with your name and image details
    image: nassafy/tpdocker:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"






